import React,{useEffect,useState,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowDown,ArrowUpRight,ChevronLeft,ChevronRight,Menu,X}from'lucide-react';
import'./style.css';

const A='/assets/';
const eras=[
 {id:'ltg',n:'01',year:'2019',title:'LAUGHTER, TEARS & GOOSEBUMPS',short:'LTG',tag:'THE DREAMER',copy:'A voice arrives fully formed—tender, restless and unafraid to feel everything.',quote:'Love, ache and ambition in the same breath.',color:'#1268d6',ink:'#eef6ff',image:A+'Fireboy DML ♡ (2).jfif',cover:A+'ltg-cover.webp',stream:'https://lnk.to/FireboyLTG',tracks:['Vibration','Jealous','King'],detail:'Thirteen songs. No guests. A debut built entirely around the clarity of his own voice. LTG introduced Afro-Life as a language for romance, anxiety and ambition—and made intimacy feel enormous.'},
 {id:'apollo',n:'02',year:'2020',title:'APOLLO',short:'APOLLO',tag:'THE ASCENSION',copy:'The dream becomes purpose. He reaches higher, expanding Afro-Life into a world of his own.',quote:'Growth sounds like courage.',color:'#00a8ff',ink:'#06111b',image:A+'Fireboy DML ♡.jfif',cover:A+'apollo-cover.jfif',stream:'https://music.apple.com/us/album/apollo/1527177191',tracks:['Champion','Tattoo','Spell'],detail:'Named for the god of music and poetry, APOLLO is evolution in motion: seventeen tracks about growth, love and pain. Fireboy moved from arrival to intention, widening the world around his Afro-Life sound.'},
 {id:'playboy',n:'03',year:'2022',title:'PLAYBOY',short:'PLAYBOY',tag:'THE STAR',copy:'The world opens. Confidence, movement and global rhythm turn intimacy into spectacle.',quote:'No borders. No apologies.',color:'#f0eee8',ink:'#111111',image:A+'Fireboy DML.jfif',cover:A+'playboy-cover.jfif',stream:'https://open.spotify.com/album/1pUJnA3OSbvVr5afqxNARZ',tracks:['Peru','Bandana','Playboy'],detail:'After Peru crossed borders, PLAYBOY met the scale of the moment. The third album traded hesitation for self-possession—fourteen songs from an artist learning how global success changes the room.'},
 {id:'adedamola',n:'04',year:'2024',title:'ADEDAMOLA',short:'ADEDAMOLA',tag:'THE MAN',copy:'Behind the name is the person—home, memory and vulnerability brought back into focus.',quote:'To go forward, he returns to himself.',color:'#17130d',ink:'#caa85b',image:A+'Adedamola.jfif',cover:A+'adedamola-cover.jfif',stream:'https://music.empi.re/adedamola',tracks:['iseoluwa','back n forth','Everyday'],detail:'The fourth album carries his birth name. Nostalgic and deeply personal, adedamola looks homeward after global success and personal loss—a portrait of the person behind the performance.'},
 {id:'zuko',n:'05',year:'2026',title:'ZUKO!',short:'ZUKO!',tag:'THE FIGHTER',copy:'Every version of Fireboy enters the ring. Refined by pressure. Sharpened by every round.',quote:'This is not a return. It is a reckoning.',color:'#d41512',ink:'#f3eee4',image:A+'HRORZUAbYAAyH-3.jfif',cover:A+'HSrlT5qbEAA7XAN.jfif',stream:'https://music.empi.re/zukofire',tracks:['CLAAT!','IMALI','ZUKO!'],detail:'The fifth act is the fighter. ZUKO! collects every former self and puts them under pressure: stripped back, sharpened and rendered in black, white and blood red.'}
];
function Countdown(){const target=new Date('2026-10-16T00:00:00+01:00');const[now,setNow]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);let d=Math.max(0,target-now);const vals=[Math.floor(d/864e5),Math.floor(d/36e5)%24,Math.floor(d/6e4)%60,Math.floor(d/1e3)%60];return <div className="count">{vals.map((v,i)=><div key={i}><b>{String(v).padStart(2,'0')}</b><span>{['DAYS','HRS','MIN','SEC'][i]}</span></div>)}</div>}
function App(){const[sound,setSound]=useState(false),[egg,setEgg]=useState(0),[game,setGame]=useState(false),[hits,setHits]=useState(0),[shift,setShift]=useState(false);const fx=(type='tap')=>{if(!sound)return;try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.setValueAtTime(type==='bell'?520:type==='hit'?90:220,c.currentTime);o.frequency.exponentialRampToValueAtTime(type==='bell'?900:45,c.currentTime+.18);g.gain.setValueAtTime(.12,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.start();o.stop(c.currentTime+.23)}catch{}};const[path,setPath]=useState(location.pathname);const go=p=>{history.pushState({},'',p);setPath(p);scrollTo(0,0)};useEffect(()=>{const h=()=>setPath(location.pathname);addEventListener('popstate',h);return()=>removeEventListener('popstate',h)},[]);const[active,setActive]=useState(4),[menu,setMenu]=useState(false),[loaded,setLoaded]=useState(false);const era=eras[active];useEffect(()=>{setTimeout(()=>setLoaded(true),1400)},[]);useEffect(()=>{document.documentElement.style.setProperty('--accent',era.color);document.documentElement.style.setProperty('--eraInk',era.ink)},[active]);const choose=i=>{setShift(true);fx('hit');setTimeout(()=>{setActive(i);setShift(false)},360);setMenu(false);setTimeout(()=>document.querySelector('#catalog').scrollIntoView({behavior:'smooth'}),50)};if(path.startsWith('/discography')){const slug=path.split('/')[2];if(slug){const item=eras.find(e=>e.id===slug)||eras[0];return <AlbumPage era={item} go={go}/>};return <Discography go={go}/>};return <main className={loaded?'loaded':''}>
 <div className="loader"><span>FIREBOY DML</span><i/></div><div className="grain"/><div className={shift?"era-wipe show":"era-wipe"}/><Cursor/><button className="sound" onClick={()=>setSound(!sound)}>{sound?"SOUND ON":"SOUND OFF"}</button><button className="ember" aria-label="Hidden fire" onClick={()=>{fx();const n=egg+1;setEgg(n);if(n>=5){setGame(true);fx("bell")}}}>♨<small>{egg>0&&egg<5?`${egg}/5`:""}</small></button>
 <header><a href="#top" className="brand">FIREBOY<br/>DML<span>♨</span></a><div className="era-label">A STORY IN FIVE ACTS </div><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <nav className={menu?'open':''}>{eras.map((e,i)=><button onClick={()=>choose(i)} key={e.id}><small>{e.n}</small>{e.short}</button>)}<a href="/discography" onClick={(e)=>{e.preventDefault();go('/discography')}}>DISCOGRAPHY →</a><a href="https://music.empi.re/zukofire" target="_blank">PRE-SAVE ZUKO! <ArrowUpRight/></a></nav>
 <section id="top" className="hero"><div className="hero-img"/><div className="hero-red"/><p className="eyebrow">FIFTH STUDIO ALBUM · 16 OCT 2026</p><h1><span>BUILT</span><span>THROUGH</span><span>FIRE.</span></h1><div className="hero-foot"><p>THE EVOLUTION OF<br/>FIREBOY DML</p><a href="#origin">ENTER THE STORY <ArrowDown/></a></div></section>
 <section id="origin" className="origin"><div className="kicker">PROLOGUE / ABEOKUTA → LAGOS</div><h2>BEFORE THE WORLD<br/>KNEW THE <em>NAME,</em><br/>THERE WAS A VOICE.</h2><div className="origin-grid"><img src={A+'Fireboy DML ♡ (1).jfif'}/><div><p>Adedamola Adefolahan found music between church, books and a growing need to say what ordinary words could not.</p><p>He moved to Lagos carrying songs. In 2018, YBNL opened the door. What followed was not one arrival—but a constant becoming.</p><span>SCROLL THROUGH THE ERAS ↓</span></div></div></section><Timeline/><Stats/>
 <section id="catalog" className="catalog" style={{background:era.color,color:era.ink}}><div className="catalog-top"><span>DISCOGRAPHY / FIVE ACTS</span><div><button onClick={()=>setActive((active+4)%5)}><ChevronLeft/></button><b>{era.n} / 05</b><button onClick={()=>setActive((active+1)%5)}><ChevronRight/></button></div></div><div className="era-stage" key={era.id}><div className="era-copy"><p>{era.year} — {era.tag}</p><h2><a href={'/discography/'+era.id} onClick={e=>{e.preventDefault();go('/discography/'+era.id)}}>{era.title}</a></h2><blockquote>“{era.quote}”</blockquote><p className="body">{era.copy}</p><a target="_blank" href={era.stream}>{era.id==='zuko'?'PRE-SAVE NOW':'STREAM THE ALBUM'} <ArrowUpRight/></a></div><div className="era-visual"><div className="number">{era.n}</div><img src={era.image}/><img className="cover" src={era.cover}/></div></div><div className="tabs">{eras.map((e,i)=><button className={i===active?'on':''} onClick={()=>setActive(i)} key={e.id}><small>{e.year}</small><span>{e.short}</span></button>)}</div></section>
 <FightRounds fx={fx}/><section className="zuko"><div className="zuko-bg"/><p>ACT V / THE FIGHTER</p><h2>ZUKO!</h2><div className="glove-strip"><img src={A+'HRORZT8awAAnuad.jfif'}/><img src={A+'HRORZUAbAAAEnPc.jfif'}/><img src={A+'HRORZUIaUAAR4hI.jfif'}/></div><div className="manifesto"><h3>PRESSURE<br/>MADE HIM.</h3><p>Four albums. A thousand lives. One artist still willing to step into the ring. ZUKO! is Fireboy stripped to instinct—black, white and blood red.</p></div></section>
 <section className="final"><p>ZUKO! ARRIVES IN</p><Countdown/><a href="https://music.empi.re/zukofire" target="_blank">PRE-SAVE THE ALBUM <ArrowUpRight/></a></section>
 {game&&<FightGame hits={hits} setHits={setHits} close={()=>{setGame(false);setHits(0)}} fx={fx}/>}<footer><div className="brand">FIREBOY<br/>DML<span>♨</span></div><div><a href="/discography" onClick={(e)=>{e.preventDefault();go('/discography')}}>DISCOGRAPHY →</a><a href="https://www.instagram.com/fireboydml" target="_blank">INSTAGRAM ↗</a><a href="https://x.com/fireboydml" target="_blank">X / TWITTER ↗</a><a href="https://www.youtube.com/@fireboydml" target="_blank">YOUTUBE ↗</a></div><small>AN UNOFFICIAL STORY EXPERIENCE<br/>© 2026 FIREBOY DML</small></footer>
 </main>}

const timeline=[['1996','ABEOKUTA','A voice begins in church, books and the private world of a quiet child.'],['OAU','ILE-IFE','English, poetry and campus stages turn writing into a possible life.'],['2018','LAGOS / YBNL','A leap toward Lagos meets Olamide. The door opens; Jealous becomes the signal.'],['2019','LTG','Thirteen songs announce Afro-Life without a single guest.'],['2020','APOLLO','Evolution, growth, love and pain—the ambition expands.'],['2021','PERU','One record crosses oceans and changes the scale of the dream.'],['2022','PLAYBOY','Global light. New confidence. A Billboard 200 arrival.'],['2024','ADEDAMOLA','He turns homeward and puts the person before the persona.'],['2026','ZUKO!','The fifth act steps into the ring.']];
function Cursor(){useEffect(()=>{const el=document.querySelector('.cursor');const m=e=>{if(el){el.style.transform=`translate(${e.clientX}px,${e.clientY}px)`}};addEventListener('pointermove',m);return()=>removeEventListener('pointermove',m)},[]);return <i className="cursor"/>}
function Timeline(){const track=useRef(null),drag=useRef({on:false,x:0,left:0});const move=d=>track.current?.scrollBy({left:d*(track.current.clientWidth*.82),behavior:'smooth'});return <section className="timeline"><div className="timeline-head"><span>THE ROAD TO ZUKO!</span><div><b>SWIPE TO EXPLORE</b><button aria-label="Previous milestone" onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label="Next milestone" onClick={()=>move(1)}><ChevronRight/></button></div></div><div className="swipe-hint"><i/> DRAG OR SWIPE</div><div ref={track} className="timeline-track" onPointerDown={e=>{drag.current={on:true,x:e.clientX,left:track.current.scrollLeft};track.current.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current.on)track.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x)}} onPointerUp={()=>drag.current.on=false} onPointerCancel={()=>drag.current.on=false}>{timeline.map((t,i)=><article key={i}><small>{String(i+1).padStart(2,'0')}</small><h3>{t[0]}</h3><h4>{t[1]}</h4><p>{t[2]}</p></article>)}</div></section>}
function Count({to,suffix=''}){const[n,setN]=useState(0);useEffect(()=>{let f=0;const id=setInterval(()=>{f+=1;setN(Math.round(to*Math.min(f/45,1)));if(f>=45)clearInterval(id)},28);return()=>clearInterval(id)},[to]);return <>{n}{suffix}</>}
function Stats(){return <section className="stats"><p>THE NUMBERS / PUBLIC STREAMING MILESTONES</p><h2>THE VOICE<br/>TRAVELLED.</h2><div className="stat-grid"><div><b><Count to={2.5} suffix="B+"/></b><span>SPOTIFY STREAMS<br/>ALL CREDITS</span></div><div><b><Count to={9.4} suffix="M"/></b><span>MONTHLY LISTENERS<br/>RECENT PUBLIC DATA</span></div><div><b>#2</b><span>PERU<br/>UK SINGLES PEAK</span></div><div><b>#53</b><span>PERU<br/>BILLBOARD HOT 100</span></div></div><small>PUBLIC FIGURES — UPDATED SEPTEMBER 2026. STREAM COUNTS CHANGE DAILY.</small></section>}
function FightRounds({fx}){const rounds=[['01','PRESSURE','The world asks who he can become.'],['02','DISCIPLINE','Every scar becomes instruction.'],['03','TRANSFORMATION','The old forms fall away.'],['FINAL','ZUKO!','The fighter answers.']];return <section className="rounds"><p>THE ZUKO! CONDITION</p>{rounds.map((r,i)=><article key={r[0]} onClick={()=>fx('hit')}><span>ROUND {r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p></article>)}</section>}
function FightGame({hits,setHits,close,fx}){const win=hits>=5;return <div className="game"><button className="game-close" onClick={close}>CLOSE ×</button>{!win?<div><small>SECRET ROUND</small><h2>FIVE<br/>HITS.</h2><button className="glove" onClick={()=>{setHits(hits+1);fx('hit')}}>🥊<b>{hits} / 5</b></button><p>TAP THE GLOVE. ENTER THE FIFTH ACT.</p></div>:<div className="game-win"><small>YOU FOUND THE FIFTH ACT</small><h2>ZUKO!</h2><img src={A+'HSrlT5qbEAA7XAN.jfif'}/><p>TO EVERYONE WHO STAYED THROUGH EVERY VERSION—<br/>THIS ROUND IS OURS.</p><a href="https://music.empi.re/zukofire" target="_blank">PRE-SAVE ↗</a></div>}</div>}

function Discography({go}){return <main className="inner"><InnerHead go={go}/><section className="disc-hero"><p>THE COMPLETE CATALOGUE / 2019—2026</p><h1>FIVE<br/>ACTS.</h1></section><section className="disc-list">{eras.map(e=><a key={e.id} href={'/discography/'+e.id} onClick={x=>{x.preventDefault();go('/discography/'+e.id)}} style={{'--c':e.color,'--i':e.ink}}><span>{e.n} / {e.year}</span><h2>{e.title}</h2><img src={e.cover}/><b>ENTER ERA ↗</b></a>)}</section></main>}
function InnerHead({go}){return <header className="inner-head"><a href="/" onClick={e=>{e.preventDefault();go('/')}} className="brand">FIREBOY<br/>DML<span>♨</span></a><a href="/" onClick={e=>{e.preventDefault();go('/')}}>CLOSE ×</a></header>}
function AlbumPage({era,go}){return <main className={'album-page '+era.id} style={{'--page':era.color,'--pageInk':era.ink}}><InnerHead go={go}/><section className="album-intro"><div className="album-meta"><span>{era.n} / 05</span><span>{era.year}</span><span>{era.tag}</span></div><h1>{era.title}</h1><img src={era.cover}/><p>{era.quote}</p></section><section className="album-story"><div><p>THE STORY</p><h2>{era.detail}</h2></div><div className="tracklist"><span>KEY RECORDS</span>{era.tracks.map((t,i)=><p key={t}><b>0{i+1}</b>{t}</p>)}</div></section><section className="album-cta"><p>LISTEN TO THE ERA</p><a href={era.stream} target="_blank">OPEN ALBUM <ArrowUpRight/></a></section><div className="next-era">{(()=>{const next=eras[(eras.indexOf(era)+1)%eras.length];return <a href={'/discography/'+next.id} onClick={e=>{e.preventDefault();go('/discography/'+next.id)}}>NEXT ACT <b>{next.title}</b> →</a>})()}</div></main>}

createRoot(document.getElementById('root')).render(<App/>);
